[package]
name = "fabela_core"
version = "0.1.0"
edition = "2024"

[dependencies]
boa_engine = "0.20.0"
faster-hex = "0.10.0"
libsui = "0.5.0"
rand = "0.9.0"
tempfile = "=3"
tokio = { workspace = true }
tracing = { workspace = true }
